### PR TITLE
Few Fixes

### PR DESCRIPTION
**Pull request by brent7320**
Fix skinplex.patch file to only modify the text for "OE Settings" without it the menu text is blank.
Modify libhid source to openelec as alioth.debian.org requires login before download
Revert d30bc0e and edd490a; these patches are in fact still needed as without them the OE Settings Menu has no text.

### CODE REVIEW

**Comment by ziggimon** [comment]
I plan to fix the menu upstream in plex code, so I would prefer not having to apply the leftsidemenu fix. The libhd fix is needed as original libhd src just keeps having downtime. And thanks for taking a crack at this while I'm swamped in other stuff. This will change soon I assure you :)

**Comment by brent7320** [comment]
No problem, took a bit but finally got it building without issues. I know how it is being swamped so i feel your pain. Great documentation on the build process, i never would have gotten it to build without it :+1:

**Comment by ziggimon** [comment]
May I close this request and later, maybe early next week push in my changes?

**Comment by brent7320** [comment]
Sounds good to me.

**Comment by ziggimon** [comment]
Closing. Fixed upstream.

**Pull request closed without merging**
